on:
  push:
    tags:
      - release.**

permissions:              # 🌟 NEW
  contents: write         # release creation / update needs this
  # discussions: write    # (only if you enable discussions on releases)
  
env:
  PYTHON_VERSION: "3.13"
  POETRY_VERSION: "2.1.3"
  POETRY_URL: https://install.python-poetry.org
  NUITKA_CACHE_DIR: ~/.nuitka/cache

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        # Do not use the latest versions in order to be backward compatible.
        # In particular, macos 14+ will build for arm only.
        # os: [macos-12, ubuntu-20.04, windows-2019]
        os: [windows-latest]
        python: [3.13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip' # caching pip dependencies

      # Install using pip / poetry-core backend via PEP 517
      - run: pip install .

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/dnb/main.py
          mode: onefile
          include-package-data: |
            dnb
            dash
            dash_core_components
            dash_html_components
            packaging
            plotly
          include-package: |
            plotly

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
